asigm_1_proj/asigm_1_app/urls.py
from xml.etree.ElementInclude import include
from django.urls import path, include

from . import views

app_name = 'asigm'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:person_id>/', views.detail, name='detail'),
    path('adduser/', views.adduser, name='adduser'),
    path('delete/<int:person_id>', views.delete, name='delete'),
]

asigm_1_proj/asigm_1_proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('asigm_1_app/', include('asigm_1_app.urls')),
    path('admin/', admin.site.urls),
    # path('user-auth/', include('user_auth.urls')),
]

asigm_1_proj/asigm_1_app/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    address = models.CharField(max_length=200)
    mobile_number = models.CharField(max_length=50)

asigm_1_proj/asigm_1_app/forms.py
from django.forms import ModelForm
from .models import Person
from django import forms

# class AddUserForm(forms.Form):
#     name =  forms.CharField(label='Full Name', max_length=100)
#     age = forms.IntegerField(label='Age', required=False)
#     address = forms.CharField(label='Address', max_length=200)
#     mobile_number = forms.CharField(label='Phone Number', max_length=50)


class AddUserForm(ModelForm):
    class Meta:
        model=Person
        fields = ['name','age','address','mobile_number']  

asigm_1_proj/asigm_1_app/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.shortcuts import get_object_or_404, render

from .forms import AddUserForm
from .models import Person
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse

def index(request):
    latest_person_list = Person.objects.all().values()
    context = {'latest_person_list': latest_person_list}
    return render(request, 'asigm_1_app/index.html', context)

def detail(request, person_id):
    try:
        person = Person.objects.get(pk=person_id)
    except Person.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'asigm_1_app/detail.html', {'person': person})

def adduser(request):
    form = AddUserForm
    if request.method == 'POST':
        form = AddUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your user has been added!')
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
        # else: # form not valid so display message and retain the data entered
        #         form = AddUserForm(request.POST)
        #         messages.success(request, 'Error in creating your user, the form is not valid!')
        #         return render(request, 'asigm_1_app/adduser.html', {'form':form})
    # else: #the form has no data
    #     form = AddUserForm() #produce a blank form
    #     return render(request, 'asigm_1_app/adduser.html', {'form':form})
    context = {'form':form}
    return render(request, 'asigm_1_app/adduser.html', context)


def delete(request, person_id):
  person = Person.objects.get(pk=person_id)
  person.delete()
  return HttpResponseRedirect(request.META['HTTP_REFERER'])

asigm_1_proj/asigm_1_app/templates/asigm_1_app/adduser.html
{% for message in messages %}
    
           {{ message }}

{% endfor %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
  
    <button type="submit" value=""> Save</button>

    <button value=""><a href="{% url 'asigm:index' %} ">Back Home</a></button>

</form>

asigm_1_proj/asigm_1_app/templates/asigm_1_app/detail.html
<h1>{{ person.name }}</h1>
<h4>Age: {{ person.age }}</h4>
<h4>Address: {{ person.address }}</h4>
<h4>Mobile Phone: {{ person.mobile_number }}</h4>

asigm_1_proj/asigm_1_app/templates/asigm_1_app/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'asigm_1_app/style.css' %}" />

{% if latest_person_list %}
<ol>
    {% for person in latest_person_list %}
    <li><a href="{% url 'asigm:detail' person.id %}" style="text-decoration: none">{{ person.name }}</a> | <a
            href="delete/{{ person.id }}" style="text-decoration: none">delete</a></li>
    {% endfor %}
</ol>
{% else %}
<p>No Data.</p>
{% endif %}

<a href="{% url 'asigm:adduser' %} ">Add New User</a>